development:
  adapter: postgresql
  encoding: unicode
  database: motels
  pool: 2
  host: localhost
  username: "postgres"
  password: Vincere21.
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
